name: instagram_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  flutter_svg: ^2.0.7
  image_picker: ^1.0.1
  firebase_app_check: ^0.1.5
  provider: ^6.0.5
  uuid: ^3.0.7
  font_awesome_flutter: ^10.5.0
  jiffy: ^6.2.1
  intl: ^0.18.1
  timeago: ^3.5.0


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
flutter_lints: ^2.0.2


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
flutter:

  uses-material-design: true

  assets:
    - assets/
