// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdYOmoPlLUGTDekO44P2m_Em9Yffli104',
    appId: '1:234993823246:web:f406fd806a0eb5eabe565f',
    messagingSenderId: '234993823246',
    projectId: 'instagram-clone-8d7df',
    authDomain: 'instagram-clone-8d7df.firebaseapp.com',
    storageBucket: 'instagram-clone-8d7df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuPohq3L7P20ydIIbjnjfl1LK9LqLaJnA',
    appId: '1:234993823246:android:5b40d7a4adc433d7be565f',
    messagingSenderId: '234993823246',
    projectId: 'instagram-clone-8d7df',
    storageBucket: 'instagram-clone-8d7df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyxFkXwSv-5crazrTlHN4x8ZFfZudn4PY',
    appId: '1:234993823246:ios:2f33cd9d4f5a8af9be565f',
    messagingSenderId: '234993823246',
    projectId: 'instagram-clone-8d7df',
    storageBucket: 'instagram-clone-8d7df.appspot.com',
    iosClientId: '234993823246-tt7u6ekvulmrkalgnidc7243460vb9ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyxFkXwSv-5crazrTlHN4x8ZFfZudn4PY',
    appId: '1:234993823246:ios:35cc993a769e556fbe565f',
    messagingSenderId: '234993823246',
    projectId: 'instagram-clone-8d7df',
    storageBucket: 'instagram-clone-8d7df.appspot.com',
    iosClientId: '234993823246-7ql6tmuonnec97s2i0phfvv86oo722d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
